# Generated by Django 5.2.1 on 2025-06-10 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Armaduras",
            fields=[
                ("id_armadura", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=70)),
                ("ca", models.IntegerField()),
                ("tipo", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Armas",
            fields=[
                ("id_armas", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=70)),
                ("dano", models.CharField(max_length=7)),
                ("tipoDano", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Ficha",
            fields=[
                ("id_ficha", models.AutoField(primary_key=True, serialize=False)),
                ("forc", models.IntegerField()),
                ("dest", models.IntegerField()),
                ("consti", models.IntegerField()),
                ("inte", models.IntegerField()),
                ("sab", models.IntegerField()),
                ("car", models.IntegerField()),
                ("forcMod", models.IntegerField()),
                ("destMod", models.IntegerField()),
                ("constiMod", models.IntegerField()),
                ("inteMod", models.IntegerField()),
                ("sabMod", models.IntegerField()),
                ("carMod", models.IntegerField()),
                ("bonusProef", models.IntegerField()),
                ("inspira", models.IntegerField()),
                ("sabPassiva", models.IntegerField()),
                ("nomePerso", models.CharField(max_length=100)),
                ("antecendente", models.CharField(max_length=70)),
                ("exp", models.IntegerField()),
                ("nivel", models.IntegerField()),
                ("classe", models.CharField(max_length=70)),
                ("alinhamento", models.CharField(max_length=70)),
                ("raca", models.CharField(max_length=70)),
                (
                    "idiomas_Proeficiencias",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                ("iniciativa", models.IntegerField()),
                ("qtd_DadosVida", models.IntegerField()),
                (
                    "ideais",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "vinculos",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "tracosPerso",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "fraquezas",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "caractHabilidades",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                ("pvTotais", models.IntegerField()),
                ("dadoVida", models.CharField(max_length=7)),
                ("deslocamento", models.FloatField()),
                ("pCobre", models.IntegerField()),
                ("pPrata", models.IntegerField()),
                ("pOuro", models.IntegerField()),
                ("pEletro", models.IntegerField()),
                ("pPlatina", models.IntegerField()),
                (
                    "descAtaque",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "descEquip",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                ("olhos", models.CharField(max_length=50)),
                ("cabelos", models.CharField(max_length=50)),
                ("idade", models.IntegerField()),
                ("altura", models.FloatField()),
                ("peso", models.FloatField()),
                ("pele", models.CharField(max_length=50)),
                (
                    "aparencia",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "aliadosOrg",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "outrasCaract",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "historia",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "tesouro",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                ("publica", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Magias",
            fields=[
                ("id_magias", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("alcance", models.FloatField()),
                ("duracao", models.CharField(max_length=60)),
                ("tempoConju", models.CharField(max_length=60)),
                ("componentes", models.CharField(max_length=40)),
                (
                    "descricao",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                ("nivel", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="CaArmadura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caMod", models.IntegerField()),
                (
                    "armadura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fichas.armaduras",
                    ),
                ),
                (
                    "ficha",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fichas.ficha",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ataque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bonus", models.IntegerField()),
                (
                    "arma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fichas.armas"
                    ),
                ),
                (
                    "ficha",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fichas.ficha",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListaMagia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("habiChave", models.CharField(max_length=70)),
                ("cdTR", models.IntegerField()),
                ("bonusAtq", models.IntegerField()),
                ("classeConju", models.CharField(max_length=100)),
                ("slot", models.CharField(max_length=30)),
                (
                    "ficha",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fichas.ficha",
                    ),
                ),
                (
                    "magia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fichas.magias"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pericias",
            fields=[
                ("id_pericias", models.AutoField(primary_key=True, serialize=False)),
                ("valor", models.IntegerField(default=2)),
                ("nome", models.CharField(max_length=40)),
                (
                    "ficha",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fichas.ficha",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(default="fulano", max_length=100)),
                ("email", models.CharField(default="email@gmail.com", max_length=70)),
                ("senha", models.CharField(default="senhaFraca")),
                (
                    "fichas",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="lista",
                        to="fichas.ficha",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ficha",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fichas.usuario"
            ),
        ),
    ]
